name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          llvm-version: 20
      - name: Build
        run: |
          make release
          mv opm opm-linux-x86_64
          sha256sum opm-linux-x86_64 > checksums.txt
      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "$GITHUB_REF_NAME" opm-linux-x86_64 checksums.txt --generate-notes --verify-tag
